Devops 2.0 helm
pagopa/selfcare-ms-product pull request #38
Opened 2022-02-28 17:05 UTC by antonioT90

2022-03-01 15:00 UTC, diegolagospagopa requested changes
completed first review, great job.

We need only to fix little things

2022-03-01 15:00 UTC, diegolagospagopa commented on .devops/deploy-pipelines.yml
> +  - name: 'skipBuild'
is better to use a positive logic like: "launchBuild" or "executeBuild",

2022-03-01 15:00 UTC, diegolagospagopa commented on .devops/deploy-pipelines.yml
> +    helmValues: values-uat.yaml
shold be better to use somethig like values-${{ lower(variables.environment) }} or remove from here and use directly into the helm task

2022-03-01 15:00 UTC, diegolagospagopa commented on .devops/deploy-pipelines.yml
> +  - stage: 'Serving_helm'
it would be better, something like "Deploy Helm", or "Helm install chart"?

2022-03-01 15:00 UTC, diegolagospagopa commented on helm/templates/configmaps.yaml
> +apiVersion: v1
Can be better to put an if to avoid to create the configMap is no values are in place

2022-03-01 15:00 UTC, diegolagospagopa commented on helm/values-prod.yaml
> +
the field: image.tag is missing for prod

2022-03-01 15:00 UTC, diegolagospagopa commented on helm/values.yaml
> +# Default values for selfcare-ms-product.
This file is still necessary? Because isn't used by pipeline. Can we migrate all the values to the env value files?

2022-03-01 18:13 UTC, antonioT90 commented on .devops/deploy-pipelines.yml
> +  - stage: 'Serving_helm'
This stage has the purpose to publish the helm charts in order to be available to the deploy stage, runned in a separate agent, avoiding to checkout again the git repo

2022-03-01 18:25 UTC, antonioT90 commented on helm/values.yaml
> +# Default values for selfcare-ms-product.
This file could make sense to exists just to hold common default values and example of configuration (even if actually disabled)

There are some common variable still inside this file and used in the pipeline (as an example, service configuration, container port and common config map values (their number could increase))

2022-03-01 18:28 UTC, antonioT90 commented on helm/templates/configmaps.yaml
> +apiVersion: v1
There will be always at least one config.

As an example each application will have:

- APPLICATIONINSIGHTS_ROLE_NAME
- JAVA_TOOL_OPTIONS
- APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL
- [APP NAME]_LOG_LEVEL

2022-03-04 11:08 UTC, diegolagospagopa commented on .devops/deploy-pipelines.yml
> +  - stage: 'Serving_helm'
publish_artifact_helm

2022-03-04 11:10 UTC, diegolagospagopa commented on helm/templates/configmaps.yaml
> +apiVersion: v1
ok

2022-03-04 11:20 UTC, diegolagospagopa approved these changes

2022-03-04 14:30 UTC, diegolagospagopa approved these changes

2022-03-04 14:31 UTC, merged