Feature/selc 1013
pagopa/selfcare-ms-product pull request #49
Opened 2022-05-12 15:54 UTC by KevinSi96

2022-05-26 13:50 UTC, rodoviti approved these changes
LGTM

2022-06-10 17:36 UTC, rodoviti requested changes

2022-06-10 17:36 UTC, rodoviti commented on web/src/main/java/it/pagopa/selfcare/product/web/model/ProductResource.java
> +    @ApiModelProperty(value = "${swagger.product.model.depictImageUrl}")
```suggestion
    @ApiModelProperty(value = "${swagger.product.model.depictImageUrl}", required = true)
```

2022-06-13 09:20 UTC, rodoviti approved these changes
LGTM

2022-06-13 16:08 UTC, antonioT90 approved these changes

2022-06-27 11:25 UTC, rodoviti approved these changes
utACK

2022-06-27 11:49 UTC, merged